name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: "12.x"
      - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: |
          npm install && npm install -g @angular/cli
          ng build --prod --base-href https://sheldonchaves.github.io/angular-mvc/ --output-path=dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
  screenshots:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - uses: actions/checkout@v2
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: "true"
      - name: remove screenshots
        run: rm -rf ./screenshots
      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@v1.0.4
        with:
          url: https://sheldonchaves.github.io/angular-mvc/
          devices: iPhone X landscape,iPhone X,iPad,Pixel 2 XL landscape,iPad Pro landscape, iPad Pro
          noDesktop: true
      - uses: actions/upload-artifact@v1
        with:
          name: Download-screenshots
          path: screenshots
      - name: setup
        run: git config --global user.email "sheldonchaves@gmail.com" && git config --global user.name "Sheldon Menezes Chaves"
      - name: rename all
        run: find ./screenshots/ -name '*.png' -exec bash -c 'echo $0 ${0/-*/.png}' {} \;
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating screenshots"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master
