name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: rename all
        run: find ./screenshots/ -name '*.png' -exec bash -c 'mv $0 ${0/-*/.png}' {} \;
